#!/usr/bin/env bash
# Self-check for tally-votes.py: the rolling window, the liberal parser, the tally, and the
# 3-vote bar with the no-change line it leaves behind. The vote bodies are generated by
# vote-issue.py and then ticked, so the parser is checked against the real generator.
set -u
cd "$(dirname "$0")/.."
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
fails=0
END=2026-08-25          # window 2026-07-26 .. 2026-08-25

ok()  { echo "ok   $1"; }
bad() { echo "FAIL $1: $2"; fails=$((fails+1)); }
jqv() { python3 -c 'import json,sys; d=json.load(open(sys.argv[1]));
[d := d[k] if isinstance(d, dict) else d[int(k)] for k in sys.argv[2].split(".")]
print(d if isinstance(d, str) else json.dumps(d))' "$1" "$2"; }
eq()  { local got; got=$(jqv "$TMP/tally.json" "$2"); [ "$got" = "$3" ] && ok "$1" ||
        bad "$1" "$2 = $got, expected $3"; }

mkdir -p "$TMP/tape"
for f in full mixed thin quiet; do
  d=$(python3 -c "import json,sys;print(json.load(open(sys.argv[1]))['date'])" "scripts/fixtures/tape-$f.json")
  cp "scripts/fixtures/tape-$f.json" "$TMP/tape/$d.json"
done

# tick <body> <n> <direction> — tick the first n boxes of that direction, in place.
tick() {
  python3 - "$@" <<'PY'
import sys
path, n, direction = sys.argv[1], int(sys.argv[2]), sys.argv[3]
out = []
for line in open(path):
    if n and f"<!--v:{direction}:" in line and line.startswith("- [ ] "):
        line, n = "- [x] " + line[6:], n - 1
    out.append(line)
open(path, "w").write("".join(out))
PY
}

# issues <file> <spec...> — each spec is number:date:created:up:down, body from that day's tape.
issues() {
  local out=$1; shift
  : >"$TMP/parts"
  for spec in "$@"; do
    IFS=: read -r num date created up down <<<"$spec"
    scripts/vote-issue.py --tape "$TMP/tape/$date.json" >"$TMP/b.md" 2>/dev/null
    tick "$TMP/b.md" "$up" up
    tick "$TMP/b.md" "$down" down
    python3 -c 'import json,sys
print(json.dumps({"number": int(sys.argv[1]), "title": f"Votes — {sys.argv[2]}",
                  "created_at": sys.argv[3] + "T22:05:11Z", "body": open(sys.argv[4]).read()}))' \
      "$num" "$date" "$created" "$TMP/b.md" >>"$TMP/parts"
  done
  python3 -c 'import json,sys; json.dump([json.loads(l) for l in open(sys.argv[1])], open(sys.argv[2],"w"))' \
    "$TMP/parts" "$out"
}

# The note file is removed first: its presence after a run is the assertion.
run() { rm -f "$TMP/note.md"; scripts/tally-votes.py --issues "$1" --tape-dir "$TMP/tape" --taste taste.md \
          --today "$END" --note "$TMP/note.md" >"$TMP/tally.json" 2>"$TMP/err"; }

# --- the tally over a window with votes on three days ----------------------------
# 2026-07-01 is 55 days back: inside the tape dir it does not exist, and its ticks must not count.
cp "$TMP/tape/2026-08-20.json" "$TMP/tape/2026-07-01.json"
issues "$TMP/issues.json" 41:2026-08-19:2026-08-18:2:0 42:2026-08-20:2026-08-19:1:1 \
                          43:2026-08-21:2026-08-20:0:0 44:2026-08-22:2026-08-21:0:0 \
                          9:2026-07-01:2026-06-30:3:3
rm "$TMP/tape/2026-07-01.json"
run "$TMP/issues.json" || { bad "tally" "$(cat "$TMP/err")"; exit 1; }

eq "the window starts a window-length back" window.start 2026-07-26
eq "the window ends today"                  window.end   "$END"
eq "up votes are counted"    votes.up    3
eq "down votes are counted"  votes.down  1
eq "the total is stated"     votes.total 4
eq "and how many days carried them" votes.days 2
eq "published days"   published.days       4
eq "items published"  published.items      10
eq "thin days"        published.thin_days  2
eq "empty days"       published.empty_days 1
eq "a voted paper carries its key and source" items.0.key 2608.18911
eq "and the day and issue behind each vote"    items.0.days.0.issue 42

# A vote issue older than the window is not counted — its six ticks would show up above.
[ "$(jqv "$TMP/tally.json" votes.total)" = 4 ] &&
  ok "a vote issue older than the window is not counted" ||
  bad "the window" "stale ticks leaked into the tally"

# ...and neither is one dated after the window end, so a rerun with an older --today
# reads the window it was given rather than everything since.
cp "$TMP/tape/2026-08-20.json" "$TMP/tape/2026-09-30.json"
issues "$TMP/future.json" 41:2026-08-19:2026-08-18:2:0 60:2026-09-30:2026-09-29:3:0
rm "$TMP/tape/2026-09-30.json"
run "$TMP/future.json"
eq "a vote issue newer than the window is not counted" votes.total 2
eq "and it is not where the no-change line goes"       note_issue 41
run "$TMP/issues.json"

# Two runs over the same window produce the same tally: no consumed marker, so a rerun
# has to be a no-op by construction.
cp "$TMP/tally.json" "$TMP/first.json"
run "$TMP/issues.json"
cmp -s "$TMP/first.json" "$TMP/tally.json" && ok "two runs produce the same tally" ||
  bad "idempotence" "a rerun changed the tally"

# --- the 3-vote bar --------------------------------------------------------------
eq "3 up votes clear the bar" clears_bar true
[ -e "$TMP/note.md" ] && bad "no note when the bar is cleared" "wrote one anyway" ||
  ok "no no-change note when the bar is cleared"

issues "$TMP/under.json" 41:2026-08-19:2026-08-18:2:0 42:2026-08-20:2026-08-19:0:2
run "$TMP/under.json"
eq "2 either way does not clear the bar" clears_bar false
eq "the votes are still counted"         votes.total 4
grep -qF "No taste change this month — 4 votes in the window" "$TMP/note.md" &&
  ok "the no-change line names the vote count" ||
  bad "the no-change line" "got: $(cat "$TMP/note.md" 2>/dev/null)"
eq "the note goes on the newest vote issue in the window" note_issue 42
grep -qE '^[-*+] \[|#[0-9]|github\.com/[^ ]*/(issues|pull)/' "$TMP/note.md" &&
  bad "the no-change line" "it is a task line or carries a cross-reference" ||
  ok "the no-change line cannot auto-tick anything"

# --- the parser stays liberal ----------------------------------------------------
python3 - "$TMP/liberal.json" <<'PY'
import json, sys
body = "\n".join([
    "- [x] 👍 more like this <!--v:up:arxiv:2608.18911-->",
    "* [X] 👍 more like this <!--v:up:arxiv:2608.19389-->",
    "+ [x] 👍 more like this <!--v:up:ssrn:10.2139/ssrn.7309901-->",
    "- [ ] 👎 less like this <!--v:down:arxiv:2608.18911-->",   # untouched: not a vote
    "- [x] 👎 less like this",                                  # no key: not a vote
])
json.dump([{"number": 50, "title": "Votes — 2026-08-20",
            "created_at": "2026-08-19T22:05:11Z", "body": body}], open(sys.argv[1], "w"))
PY
run "$TMP/liberal.json"
eq "'-', '*' and '+' with either case of x all count" votes.up   3
eq "an empty box is not a vote"                       votes.down 0
n=$(python3 -c 'import json,sys;print(len(json.load(open(sys.argv[1]))["items"]))' "$TMP/tally.json")
[ "$n" -eq 3 ] && ok "three distinct papers, one vote each" ||
  bad "distinct papers" "counted $n keys, expected 3"

# --- the workflow reads them the way §6 rule 6 says ------------------------------
W=.github/workflows/monthly-taste.yml
whas() { grep -qF -- "$2" "$W" && ok "$1" || bad "$1" "monthly-taste.yml lacks '$2'"; }
whas "monthly, matching the window" 'cron: "0 23 1 * *"'
whas "dispatch is the retry"        "workflow_dispatch:"
whas "one run at a time"            "group: research-tape-monthly"
whas "votes are read by label listing" 'issues?labels=vote'
whas "one fetch per issue body"        'repos/$REPO/issues/$n'
whas "the tally runs over the same window" "tally-votes.py"
whas "the no-change line is posted"        "gh issue comment"
grep -q "search/issues" "$W" && bad "never the search API" "monthly-taste.yml calls /search/issues" ||
  ok "the search API is never called"

[ "$fails" -eq 0 ] && echo "all tally-votes checks passed" || echo "$fails check(s) failed"
exit $((fails > 0))
